import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content="Triconedigital - web development agency"/>

    <title>Tricone Digital -Web Agency</title>
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="/assets/css/font-awesome.min.css" rel="stylesheet"/>
    <link href="/assets/css/themify-icons.css" rel="stylesheet"/>
    <link href="/assets/css/elegant-icons.css" rel="stylesheet"/>
    <link href="/assets/css/flaticon-set.css" rel="stylesheet"/>
    <link href="/assets/css/magnific-popup.css" rel="stylesheet"/>
    <link href="/assets/css/swiper-bundle.min.css" rel="stylesheet"/>
    <link href="/assets/css/animate.css" rel="stylesheet"/>
    <link href="/assets/css/validnavs.css" rel="stylesheet"/>
    <link href="/assets/css/helper.css" rel="stylesheet"/>
    <link href="/assets/css/unit-test.css" rel="stylesheet"/>
    <link href="/assets/css/style.css" rel="stylesheet"/>
      </head>
      <body className={inter.className}>
        
        {children}
        
        </body>
      <script src="/assets/js/jquery-3.6.0.min.js"></script>
    <script src="/assets/js/bootstrap.bundle.min.js"></script>
    <script src="/assets/js/jquery.appear.js"></script>
    <script src="/assets/js/jquery.easing.min.js"></script>
    <script src="/assets/js/jquery.magnific-popup.min.js"></script>
    <script src="/assets/js/modernizr.custom.13711.js"></script>
    <script src="/assets/js/swiper-bundle.min.js"></script>
    <script src="/assets/js/wow.min.js"></script>
    <script src="/assets/js/progress-bar.min.js"></script>
    <script src="/assets/js/circle-progress.js"></script>
    <script src="/assets/js/isotope.pkgd.min.js"></script>
    <script src="/assets/js/imagesloaded.pkgd.min.js"></script>
    <script src="/assets/js/jquery.nice-select.min.js"></script>
    <script src="/assets/js/count-to.js"></script>
    <script src="/assets/js/jquery.scrolla.min.js"></script>
    <script src="/assets/js/YTPlayer.min.js"></script>
    <script src="/assets/js/TweenMax.min.js"></script>
    <script src="/assets/js/rangeSlider.min.js"></script>
    <script src="/assets/js/jquery-ui.min.js"></script>
    <script src="/assets/js/validnavs.js"></script>
    <script src="/assets/js/main.js"></script>
    </html>
  );
}
